package com.rho.cli.api.doctor;

public enum Specialization {
    CARDIOLOGIST,
    DERMATOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    GYNECOLOGIST,
    HEMATOLOGIST,
    NEPHROLOGIST,
    NEUROLOGIST,
    OPHTHALMOLOGIST,
    OTOLARYNGOLOGIST,
    PEDIATRICIAN,
    PSYCHIATRIST,
    PULMONOLOGIST,
    UROLOGIST,
    OTHER
}
